In [1]:
import torch
from model import TimeSeriesBinaryClassificationModel

In [2]:
model = TimeSeriesBinaryClassificationModel()

In [3]:
for i in model.encoder1.lstm1.named_parameters():
    print(i)

('weight_ih_l0', Parameter containing:
tensor([[-0.0406,  0.0160, -0.0224,  ..., -0.0364,  0.0108, -0.0148],
        [ 0.0061, -0.0067,  0.0622,  ..., -0.0338, -0.0173, -0.0329],
        [-0.0719,  0.0059, -0.0076,  ..., -0.0112,  0.0166,  0.0043],
        ...,
        [-0.0358,  0.0002,  0.0102,  ..., -0.0363,  0.0455, -0.0142],
        [-0.0153,  0.0215,  0.0093,  ..., -0.0379,  0.0314,  0.0122],
        [-0.0046,  0.0287, -0.0171,  ...,  0.0107,  0.0327,  0.0122]],
       requires_grad=True))
('weight_hh_l0', Parameter containing:
tensor([[-9.7675e-03,  4.6852e-03, -6.3323e-06,  ..., -2.0813e-02,
         -1.3865e-02, -3.1472e-02],
        [-1.8379e-03,  4.6058e-02,  1.6412e-02,  ...,  3.0498e-02,
          2.0821e-02, -1.0376e-02],
        [ 9.9060e-03, -2.8729e-02,  1.7452e-02,  ...,  8.0564e-03,
         -8.5679e-03, -5.3516e-03],
        ...,
        [ 1.0556e-02,  2.3925e-02, -3.3383e-02,  ..., -1.9190e-02,
         -1.1807e-02,  5.8773e-04],
        [ 1.7498e-02,  8.0511e-03, 

In [3]:
for i in model.head.named_parameters():
    print(i)

('weight', Parameter containing:
tensor([[ 4.8500e-01,  2.3566e-01,  3.8405e-01, -2.0698e+00,  1.7120e+00,
         -2.1115e-02, -1.4670e+00,  1.7274e+00, -5.5192e-01, -7.5216e-01,
         -1.2328e+00, -4.0519e-01, -1.6746e+00,  4.2106e-01,  3.2033e-01,
          6.2815e-01,  4.4205e-02, -1.3771e+00,  2.1896e+00,  9.7848e-01,
         -1.7810e-01,  2.0713e-01,  7.4360e-01,  2.0583e+00, -3.3752e-01,
         -3.8259e-01,  3.1237e+00, -5.1498e-01,  1.4768e+00,  5.1699e-02,
          8.1080e-01, -7.4553e-01,  2.3621e+00,  2.8715e-03, -1.1209e+00,
          1.6088e+00, -3.0993e-01, -1.3650e+00,  1.7028e+00, -6.1942e-02,
          6.0650e-01,  8.1578e-01, -1.9199e-01, -1.2931e+00, -7.3932e-01,
         -9.8896e-01, -1.6122e-01,  2.9648e+00, -4.5833e-01, -4.9642e-01,
          1.7495e+00,  1.6617e+00, -1.6178e+00,  1.5380e+00, -1.4399e+00,
         -2.4257e+00, -3.5572e-01,  5.9664e-01,  1.9154e-01,  1.1530e+00,
          1.0290e+00, -5.3242e-01, -1.0451e+00,  5.5875e-01, -2.8997e-01,
     

In [4]:
for i in model.head.named_parameters():
    print(i)

('weight', Parameter containing:
tensor([[-2.1415e-02, -2.1829e-02,  2.6230e-02, -8.5193e-02, -7.6632e-03,
         -6.8072e-02, -2.7203e-02,  6.1720e-02, -4.9478e-02,  4.5603e-02,
         -6.2651e-02, -6.4799e-02,  4.7228e-02, -3.8508e-02,  7.0029e-02,
          7.0463e-02, -6.5248e-03, -8.3257e-02,  4.4128e-02,  1.9718e-02,
          3.1181e-02, -2.4495e-02,  1.3701e-02, -8.1331e-05,  2.4963e-02,
          2.0878e-02, -8.8129e-02,  6.9786e-02,  5.0003e-02, -8.4549e-02,
          4.5629e-03,  7.5199e-02, -3.4062e-02, -7.5300e-02, -7.5046e-02,
          8.0921e-02,  6.3192e-03,  3.5548e-02,  1.1269e-02, -1.7107e-02,
          5.6209e-02,  4.5600e-02, -2.5007e-02, -8.2276e-02, -3.2640e-03,
          4.0312e-02, -4.7252e-02, -4.8563e-02,  5.8963e-02, -3.2745e-02,
          8.8103e-02, -3.8999e-02, -6.4064e-02,  2.5091e-02, -4.9172e-02,
         -4.1452e-02,  3.7005e-02,  4.6329e-02,  1.9293e-02, -5.1226e-02,
          3.4172e-02,  6.1813e-02, -7.9402e-02,  7.7264e-02,  5.4713e-02,
     

In [8]:
model(torch.rand(3, 2, 30))

/Users/lincolnfong/opt/anaconda3/envs/COMP7509/lib/python3.10/site-packages/torch/nn/modules/conv.py:306: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Convolution.cpp:1009.)
  return F.conv1d(input, weight, bias, self.stride,


tensor([[-0.0024],
        [-0.0024],
        [-0.0024]], grad_fn=<AddmmBackward0>)

In [10]:
torch.rand(3, 2, 7)[:,0,:].size()

torch.Size([3, 7])

In [14]:
torch.nn.BCEWithLogitsLoss()(torch.tensor([[-0.0364],
        [-0.0364],
        [-0.0364],
        [-0.0364],
        [-0.0364],
        [-0.0364],
        [-0.0364],
        [-0.0364]]),torch.tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]))

tensor(0.6751)

In [27]:
torch.nn.BCEWithLogitsLoss()(torch.tensor([-10.]*8), torch.tensor([0.]*8))

tensor(4.5418e-05)

In [12]:
torch.tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

tensor([[0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [10]:
import torch
from torchmetrics.classification import Recall, Precision

In [14]:
recall = Recall(task="multiclass", average='none', num_classes=2)
precision = Precision(task="multiclass", average='none', num_classes=2)

In [15]:
preds  = torch.tensor([1, 0, 1, 1])
target = torch.tensor([1, 1, 0, 0])

In [16]:
recall(preds, target)

tensor([0.0000, 0.5000])

In [17]:
precision(preds, target)

tensor([0.0000, 0.3333])

In [18]:
Recall(task="multiclass", average='macro', num_classes=2)(preds,target)

tensor(0.2500)

In [19]:
metrics = ["bull_recall",
"bear_recall",
"bull_precision",
"bear_precision",
"bull_f1_score",
"bear_f1_score"]

running_metrics = {k: 0. for k in metrics}

In [20]:
running_metrics

{'bull_recall': 0.0,
 'bear_recall': 0.0,
 'bull_precision': 0.0,
 'bear_precision': 0.0,
 'bull_f1_score': 0.0,
 'bear_f1_score': 0.0}

In [21]:
import numpy as np
data = np.load("datasets.npz")

In [24]:
data["mid_x"].shape

(2450, 15, 5)

In [26]:
np.empty(data["mid_x"].shape[1:]).shape

(15, 5)

In [40]:
def process(data):
    m = np.empty((data.shape[0], 1, 5, 7))
    for i, x in enumerate(data):
        n = np.empty((5, 7))
        for j, v in enumerate(x.T):
            n[j] = np.interp(np.array(list(range(7)))*len(v)/7, range(len(v)), v)
        n = np.expand_dims(n, 0)
        m[i] = n
    return m

In [72]:
data["short_y"][30 - 7:2000+7][:10]

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

In [74]:
data["mid_y"][30 - 15:2000+15][:10]

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

In [76]:
data["long_y"][:2000][:10]

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1])

In [60]:
data["long_y"][:][:20]

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0])

In [61]:
data["mid_y"][30-15:][:20]

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0])

In [87]:
torch.rand((1,2,3,4))[:,:,[0],:].size()

torch.Size([1, 2, 1, 4])